In [1]:
%pip install pymysql

Collecting pymysql
  Using cached pymysql-1.2.0-py3-none-any.whl.metadata (4.3 kB)
Using cached pymysql-1.2.0-py3-none-any.whl (45 kB)
Installing collected packages: pymysql
Successfully installed pymysql-1.2.0
Note: you may need to restart the kernel to use updated packages.

In [7]:
import pandas as pd

# 讀取 csv 檔案
df = pd.read_csv('./Sample-Superstore.csv', encoding='latin1')
df.head()

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
0,1,CA-2016-152156,11/8/2016,11/11/2016,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.9600,2,0.00,41.9136
1,2,CA-2016-152156,11/8/2016,11/11/2016,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400,3,0.00,219.5820
2,3,CA-2016-138688,6/12/2016,6/16/2016,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,...,90036,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.6200,2,0.00,6.8714
3,4,US-2015-108966,10/11/2015,10/18/2015,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775,5,0.45,-383.0310
4,5,US-2015-108966,10/11/2015,10/18/2015,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.3680,2,0.20,2.5164

In [3]:
import pymysql
from configparser import ConfigParser
from create_table import create_superstore_tables

# 讀取 .env 檔案取得資料庫連線資訊
config = ConfigParser()
config.read('../Chapter1/config.ini')

# 建立資料庫連線
connection = pymysql.connect(
    host=config.get('DB', 'host'),
    user=config.get('DB', 'user'),
    password=config.get('DB', 'password'),
    port=config.getint('DB', 'port'),
    cursorclass=pymysql.cursors.DictCursor,
)

with connection.cursor() as cursor:
    # 建立資料庫
    cursor.execute(f"CREATE DATABASE IF NOT EXISTS superstore")
    cursor.execute(f"SHOW DATABASES")
    dbs = cursor.fetchall()
    print(dbs)

    # 建立資料表
    create_superstore_tables('superstore')

[{'Database': 'chapter2'}, {'Database': 'chapter3'}, {'Database': 'classicmodels'}, {'Database': 'information_schema'}, {'Database': 'my_database'}, {'Database': 'my_titanic'}, {'Database': 'my_train_titanic'}, {'Database': 'mysql'}, {'Database': 'performance_schema'}, {'Database': 'sakila'}, {'Database': 'social_media_app'}, {'Database': 'superstore'}, {'Database': 'sys'}, {'Database': 'testdb'}, {'Database': 'transaction_test'}, {'Database': 'world'}]
{'Tables_in_superstore': 'customers'}
{'Tables_in_superstore': 'orderdetails'}
{'Tables_in_superstore': 'orders'}
{'Tables_in_superstore': 'products'}

In [20]:
# 建立資料庫連線
connection = pymysql.connect(
    host=config.get('DB', 'host'),
    user=config.get('DB', 'user'),
    password=config.get('DB', 'password'),
    port=config.getint('DB', 'port'),
    cursorclass=pymysql.cursors.DictCursor,
    database='superstore'
)

In [17]:
import pandas as pd

# 讀取 CSV 檔案
df = pd.read_csv('./Sample-Superstore.csv', encoding='latin1')
# df.head()
print(df.columns)

# 提取客戶欄位的資料
customers = df[['Customer ID', 'Customer Name', 'Segment']]
# 去除重複的客戶資料
customers = customers.drop_duplicates()

customers

Index(['Row ID', 'Order ID', 'Order Date', 'Ship Date', 'Ship Mode',
       'Customer ID', 'Customer Name', 'Segment', 'Country', 'City', 'State',
       'Postal Code', 'Region', 'Product ID', 'Category', 'Sub-Category',
       'Product Name', 'Sales', 'Quantity', 'Discount', 'Profit'],
      dtype='object')

     Customer ID      Customer Name      Segment
0       CG-12520        Claire Gute     Consumer
2       DV-13045    Darrin Van Huff    Corporate
3       SO-20335     Sean O'Donnell     Consumer
5       BH-11710    Brosina Hoffman     Consumer
12      AA-10480       Andrew Allen     Consumer
...          ...                ...          ...
8666    CJ-11875       Carl Jackson    Corporate
9209    RS-19870         Roy Skaria  Home Office
9399    SC-20845         Sung Chung     Consumer
9441    RE-19405    Ricardo Emerson     Consumer
9558    SM-20905  Susan MacKendrick     Consumer

[793 rows x 3 columns]

Customers

In [ ]:
import pandas as pd

# 讀取 CSV 檔案
df = pd.read_csv('./Sample-Superstore.csv', encoding='latin1')
# df.head()
print(df.columns)

# 提取客戶欄位的資料
customers = df[['Customer ID', 'Customer Name', 'Segment']]
# 去除重複的客戶資料
customers = customers.drop_duplicates()

# 轉成 list 以便後續寫入
customers_list = customers.values.tolist()
print(customers_list)

# 寫入 Customers 資料表
with connection.cursor() as cursor:
    sql = """
        INSERT INTO customers (customer_id, customer_name, segment)
        VALUES (%s, %s, %s);
    """
    # cursor.executemany(sql, customers_list) # 執行過就先註解起來，避免重複寫入
    
    cursor.execute('SELECT * FROM customers;')
    result = cursor.fetchall()
    print(result)

    connection.commit()

[['CG-12520', 'Claire Gute', 'Consumer'], ['DV-13045', 'Darrin Van Huff', 'Corporate'], ['SO-20335', "Sean O'Donnell", 'Consumer'], ['BH-11710', 'Brosina Hoffman', 'Consumer'], ['AA-10480', 'Andrew Allen', 'Consumer'], ['IM-15070', 'Irene Maddox', 'Consumer'], ['HP-14815', 'Harold Pawlan', 'Home Office'], ['PK-19075', 'Pete Kriz', 'Consumer'], ['AG-10270', 'Alejandro Grove', 'Consumer'], ['ZD-21925', 'Zuschuss Donatelli', 'Consumer'], ['KB-16585', 'Ken Black', 'Corporate'], ['SF-20065', 'Sandra Flanagan', 'Consumer'], ['EB-13870', 'Emily Burns', 'Consumer'], ['EH-13945', 'Eric Hoffmann', 'Consumer'], ['TB-21520', 'Tracy Blumstein', 'Consumer'], ['MA-17560', 'Matt Abelman', 'Home Office'], ['GH-14485', 'Gene Hale', 'Corporate'], ['SN-20710', 'Steve Nguyen', 'Home Office'], ['LC-16930', 'Linda Cazamias', 'Corporate'], ['RA-19885', 'Ruben Ausman', 'Corporate'], ['ES-14080', 'Erin Smith', 'Corporate'], ['ON-18715', 'Odella Nelson', 'Corporate'], ['PO-18865', "Patrick O'Donnell", 'Consumer'], ['LH-16900', 'Lena Hernandez', 'Consumer'], ['DP-13000', 'Darren Powers', 'Consumer'], ['JM-15265', 'Janet Molinari', 'Corporate'], ['TB-21055', 'Ted Butterfield', 'Consumer'], ['KM-16720', 'Kunst Miller', 'Consumer'], ['PS-18970', 'Paul Stevenson', 'Home Office'], ['BS-11590', 'Brendan Sweed', 'Corporate'], ['KD-16270', 'Karen Daniels', 'Consumer'], ['HM-14980', 'Henry MacAllister', 'Consumer'], ['JE-15745', 'Joel Eaton', 'Consumer'], ['KB-16600', 'Ken Brennan', 'Corporate'], ['SC-20770', 'Stewart Carmichael', 'Corporate'], ['DN-13690', 'Duane Noonan', 'Consumer'], ['JC-16105', 'Julie Creighton', 'Corporate'], ['CS-12400', 'Christopher Schild', 'Home Office'], ['PG-18895', 'Paul Gonzalez', 'Consumer'], ['GM-14455', 'Gary Mitchum', 'Home Office'], ['JS-15685', 'Jim Sink', 'Corporate'], ['KB-16315', 'Karl Braun', 'Consumer'], ['RB-19705', 'Roger Barcio', 'Home Office'], ['PN-18775', 'Parhena Norris', 'Home Office'], ['KD-16345', 'Katherine Ducich', 'Consumer'], ['ER-13855', 'Elpida Rittenbach', 'Corporate'], ['RB-19465', 'Rick Bensley', 'Home Office'], ['GZ-14470', 'Gary Zandusky', 'Consumer'], ['LC-16870', 'Lena Cacioppo', 'Consumer'], ['JM-15250', 'Janet Martin', 'Consumer'], ['PA-19060', 'Pete Armstrong', 'Home Office'], ['CV-12805', 'Cynthia Voltz', 'Corporate'], ['CL-12565', 'Clay Ludtke', 'Consumer'], ['RC-19960', 'Ryan Crowe', 'Consumer'], ['DK-13090', 'Dave Kipp', 'Consumer'], ['GG-14650', 'Greg Guthrie', 'Corporate'], ['SC-20725', 'Steven Cartwright', 'Consumer'], ['AD-10180', 'Alan Dominguez', 'Home Office'], ['PF-19165', 'Philip Fox', 'Consumer'], ['TS-21610', 'Troy Staebel', 'Consumer'], ['LS-16975', 'Lindsay Shagiari', 'Home Office'], ['DW-13585', 'Dorothy Wardle', 'Corporate'], ['LC-16885', 'Lena Creighton', 'Consumer'], ['JD-15895', 'Jonathan Doherty', 'Corporate'], ['SH-19975', 'Sally Hughsby', 'Corporate'], ['SG-20080', 'Sandra Glassco', 'Consumer'], ['HA-14920', 'Helen Andreada', 'Consumer'], ['MG-17680', 'Maureen Gastineau', 'Home Office'], ['JE-16165', 'Justin Ellison', 'Corporate'], ['TW-21025', 'Tamara Willingham', 'Home Office'], ['SP-20650', 'Stephanie Phelps', 'Corporate'], ['NK-18490', 'Neil Knudson', 'Home Office'], ['DB-13060', 'Dave Brooks', 'Consumer'], ['NP-18670', 'Nora Paige', 'Consumer'], ['TT-21070', 'Ted Trevino', 'Consumer'], ['EM-13960', 'Eric Murdock', 'Consumer'], ['RD-19900', 'Ruben Dartt', 'Consumer'], ['MJ-17740', 'Max Jones', 'Consumer'], ['BM-11140', 'Becky Martin', 'Consumer'], ['CS-12130', 'Chad Sievert', 'Consumer'], ['JB-15400', 'Jennifer Braxton', 'Corporate'], ['SJ-20500', 'Shirley Jackson', 'Consumer'], ['JK-15640', 'Jim Kriz', 'Home Office'], ['DK-13150', 'David Kendrick', 'Corporate'], ['RM-19675', 'Robert Marley', 'Home Office'], ['SK-19990', 'Sally Knutson', 'Consumer'], ['FM-14290', 'Frank Merwin', 'Home Office'], ['AM-10360', 'Alice McCarthy', 'Corporate'], ['MP-17470', 'Mark Packer', 'Home Office'], ['MZ-17515', 'Mary Zewe', 'Corporate'], ['CB-12025', 'Cassandra Brandow', 'Consumer'], ['VM-21685', 'Valerie Mitchum', 'Home Office'], ['FH-14365', 'Fred Hopkins', 'Corporate'], ['MB-17305', 'Maria Bertelson', 'Consumer'], ['BS-11755', 'Bruce Stewart', 'Consumer'], ['LC-17140', 'Logan Currie', 'Consumer'], ['HK-14890', 'Heather Kirkland', 'Corporate'], ['LE-16810', 'Laurel Elliston', 'Consumer'], ['JH-15985', 'Joseph Holt', 'Consumer'], ['MS-17980', 'Michael Stewart', 'Corporate'], ['VW-21775', 'Victoria Wilson', 'Corporate'], ['JH-15910', 'Jonathan Howell', 'Consumer'], ['JB-15925', 'Joni Blumstein', 'Consumer'], ['DS-13180', 'David Smith', 'Corporate'], ['VD-21670', 'Valerie Dominguez', 'Consumer'], ['EA-14035', 'Erin Ashbrook', 'Corporate'], ['DB-13120', 'David Bremer', 'Corporate'], ['KL-16645', 'Ken Lonsdale', 'Consumer'], ['DW-13480', 'Dianna Wilson', 'Home Office'], ['LH-17155', 'Logan Haushalter', 'Consumer'], ['KC-16540', 'Kelly Collister', 'Consumer'], ['DL-13315', 'Delfina Latchford', 'Consumer'], ['DR-12880', 'Dan Reichenbach', 'Corporate'], ['CC-12670', 'Craig Carreira', 'Consumer'], ['Dl-13600', 'Dorris liebe', 'Corporate'], ['SB-20290', 'Sean Braxton', 'Corporate'], ['RC-19825', 'Roy Collins', 'Consumer'], ['AH-10210', 'Alan Hwang', 'Consumer'], ['CB-12535', 'Claudia Bergmann', 'Corporate'], ['CA-12310', 'Christine Abelman', 'Corporate'], ['KH-16690', 'Kristen Hastings', 'Corporate'], ['BB-10990', 'Barry Blumstein', 'Corporate'], ['AG-10495', 'Andrew Gjertsen', 'Corporate'], ['JO-15280', "Jas O'Carroll", 'Consumer'], ['AH-10195', 'Alan Haines', 'Corporate'], ['NZ-18565', 'Nick Zandusky', 'Home Office'], ['KL-16555', 'Kelly Lampkin', 'Corporate'], ['AS-10225', 'Alan Schoenberger', 'Corporate'], ['CR-12625', 'Corey Roper', 'Home Office'], ['SH-20395', 'Shahid Hopkins', 'Consumer'], ['BP-11185', 'Ben Peterman', 'Corporate'], ['TS-21205', 'Thomas Seio', 'Corporate'], ['AG-10525', 'Andy Gerbode', 'Corporate'], ['SP-20860', 'Sung Pak', 'Corporate'], ['NM-18445', 'Nathan Mautz', 'Home Office'], ['FA-14230', 'Frank Atkinson', 'Corporate'], ['GK-14620', 'Grace Kelly', 'Corporate'], ['DJ-13510', 'Don Jones', 'Corporate'], ['PO-18850', "Patrick O'Brill", 'Consumer'], ['JL-15850', 'John Lucas', 'Consumer'], ['DB-13615', 'Doug Bickford', 'Consumer'], ['AC-10420', 'Alyssa Crouse', 'Corporate'], ['CC-12550', 'Clay Cheatham', 'Consumer'], ['TD-20995', 'Tamara Dahlen', 'Consumer'], ['AB-10060', 'Adam Bellavance', 'Home Office'], ['JL-15505', 'Jeremy Lonsdale', 'Consumer'], ['VB-21745', 'Victoria Brennan', 'Corporate'], ['KW-16435', 'Katrina Willman', 'Consumer'], ['JD-16060', 'Julia Dunbar', 'Consumer'], ['MK-17905', 'Michael Kennedy', 'Corporate'], ['GT-14755', 'Guy Thornton', 'Consumer'], ['AG-10900', 'Arthur Gainer', 'Consumer'], ['MM-18280', 'Muhammed MacIntyre', 'Corporate'], ['AR-10405', 'Allen Rosenblatt', 'Corporate'], ['RA-19915', 'Russell Applegate', 'Consumer'], ['AS-10285', 'Alejandro Savely', 'Corporate'], ['LA-16780', 'Laura Armstrong', 'Corporate'], ['DO-13435', 'Denny Ordway', 'Consumer'], ['DK-13225', 'Dean Katz', 'Corporate'], ['NG-18430', 'Nathan Gelder', 'Consumer'], ['MV-18190', 'Mike Vittorini', 'Consumer'], ['JG-15115', 'Jack Garza', 'Consumer'], ['BP-11095', 'Bart Pistole', 'Corporate'], ['VP-21730', 'Victor Preis', 'Home Office'], ['SS-20140', 'Saphhira Shifley', 'Corporate'], ['AG-10675', 'Anna Gayman', 'Consumer'], ['LF-17185', 'Luke Foster', 'Consumer'], ['RF-19840', 'Roy Französisch', 'Consumer'], ['KH-16510', 'Keith Herrera', 'Consumer'], ['KC-16675', 'Kimberly Carter', 'Corporate'], ['CJ-12010', 'Caroline Jumper', 'Consumer'], ['PB-19150', 'Philip Brown', 'Consumer'], ['MP-17965', 'Michael Paige', 'Corporate'], ['NF-18385', 'Natalie Fritzler', 'Consumer'], ['SD-20485', 'Shirley Daniels', 'Home Office'], ['KH-16630', 'Ken Heidel', 'Corporate'], ['RB-19795', 'Ross Baird', 'Home Office'], ['MK-18160', 'Mike Kennedy', 'Consumer'], ['PO-19180', 'Philisse Overcash', 'Home Office'], ['BB-11545', 'Brenda Bowman', 'Corporate'], ['TB-21595', 'Troy Blackwell', 'Consumer'], ['RB-19360', 'Raymond Buch', 'Consumer'], ['EB-13705', 'Ed Braxton', 'Corporate'], ['SC-20095', 'Sanjit Chand', 'Consumer'], ['TN-21040', 'Tanja Norvell', 'Home Office'], ['JS-15940', 'Joni Sundaresam', 'Home Office'], ['MH-17785', 'Maya Herman', 'Corporate'], ['JP-15520', 'Jeremy Pistek', 'Consumer'], ['JE-15475', 'Jeremy Ellison', 'Consumer'], ['JG-15805', 'John Grady', 'Corporate'], ['XP-21865', 'Xylona Preis', 'Consumer'], ['EM-14065', 'Erin Mull', 'Consumer'], ['MT-18070', 'Michelle Tran', 'Home Office'], ['SA-20830', 'Sue Ann Reed', 'Consumer'], ['CW-11905', 'Carl Weiss', 'Home Office'], ['AJ-10960', 'Astrea Jones', 'Consumer'], ['SS-20590', 'Sonia Sunley', 'Consumer'], ['RO-19780', "Rose O'Brian", 'Consumer'], ['MD-17350', 'Maribeth Dona', 'Consumer'], ['MY-17380', 'Maribeth Yedwab', 'Corporate'], ['CM-12385', 'Christopher Martinez', 'Consumer'], ['LS-17245', 'Lynn Smith', 'Consumer'], ['BN-11515', 'Bradley Nguyen', 'Consumer'], ['DB-13210', 'Dean Braden', 'Consumer'], ['MC-17605', 'Matt Connell', 'Corporate'], ['BD-11605', 'Brian Dahlen', 'Consumer'], ['PH-18790', 'Patricia Hirasaki', 'Home Office'], ['MG-18145', 'Mike Gockenbach', 'Consumer'], ['KB-16240', 'Karen Bern', 'Corporate'], ['JC-15340', 'Jasper Cacioppo', 'Consumer'], ['RL-19615', 'Rob Lucas', 'Consumer'], ['AA-10375', 'Allen Armold', 'Consumer'], ['EP-13915', 'Emily Phan', 'Consumer'], ['DK-12985', 'Darren Koutras', 'Consumer'], ['BD-11500', 'Bradley Drucker', 'Consumer'], ['LM-17065', 'Liz MacKendrick', 'Consumer'], ['AS-10135', 'Adrian Shami', 'Home Office'], ['BD-11320', 'Bill Donatelli', 'Consumer'], ['GT-14710', 'Greg Tran', 'Consumer'], ['AJ-10945', 'Ashley Jarboe', 'Consumer'], ['OT-18730', 'Olvera Toch', 'Consumer'], ['LP-17080', 'Liz Pelletier', 'Consumer'], ['CA-12775', 'Cynthia Arntzen', 'Consumer'], ['JF-15490', 'Jeremy Farry', 'Consumer'], ['FP-14320', 'Frank Preis', 'Consumer'], ['EB-13840', 'Ellis Ballard', 'Corporate'], ['JF-15415', 'Jennifer Ferguson', 'Consumer'], ['SF-20200', 'Sarah Foster', 'Consumer'], ['TG-21640', 'Trudy Glocke', 'Consumer'], ['CS-11950', 'Carlos Soltero', 'Consumer'], ['CC-12145', 'Charles Crestani', 'Consumer'], ['DV-13465', 'Dianna Vittorini', 'Consumer'], ['BD-11725', 'Bruce Degenhardt', 'Consumer'], ['ZC-21910', 'Zuschuss Carroll', 'Consumer'], ['MS-17830', 'Melanie Seite', 'Consumer'], ['LR-16915', 'Lena Radford', 'Consumer'], ['TP-21130', 'Theone Pippenger', 'Consumer'], ['CK-12205', 'Chloris Kastensmidt', 'Consumer'], ['AS-10240', 'Alan Shonely', 'Consumer'], ['AR-10510', 'Andrew Roberts', 'Consumer'], ['NB-18655', 'Nona Balk', 'Corporate'], ['GD-14590', 'Giulietta Dortch', 'Corporate'], ['CK-12595', 'Clytie Kelty', 'Consumer'], ['NG-18355', 'Nat Gilpin', 'Corporate'], ['CA-12265', 'Christina Anderson', 'Consumer'], ['SF-20965', 'Sylvia Foulston', 'Corporate'], ['MO-17800', "Meg O'Connel", 'Home Office'], ['AT-10735', 'Annie Thurman', 'Consumer'], ['FM-14380', 'Fred McMath', 'Consumer'], ['DJ-13420', 'Denny Joy', 'Corporate'], ['ME-17725', 'Max Engle', 'Consumer'], ['JD-16150', 'Justin Deggeller', 'Corporate'], ['JL-15835', 'John Lee', 'Consumer'], ['SC-20305', 'Sean Christensen', 'Consumer'], ['CC-12430', 'Chuck Clark', 'Home Office'], ['AR-10825', 'Anthony Rawles', 'Corporate'], ['SR-20740', 'Steven Roelle', 'Home Office'], ['CR-12730', 'Craig Reiter', 'Consumer'], ['EH-14125', 'Eugene Hildebrand', 'Home Office'], ['SP-20545', 'Sibella Parks', 'Corporate'], ['TH-21235', 'Tiffany House', 'Corporate'], ['RP-19390', 'Resi Pölking', 'Consumer'], ['RB-19570', 'Rob Beeghly', 'Consumer'], ['CD-11980', 'Carol Darley', 'Consumer'], ['DJ-13630', 'Doug Jacobs', 'Consumer'], ['GT-14635', 'Grant Thornton', 'Corporate'], ['MC-17845', 'Michael Chen', 'Consumer'], ['RA-19285', 'Ralph Arnett', 'Consumer'], ['NP-18325', 'Naresj Patel', 'Consumer'], ['AB-10165', 'Alan Barnes', 'Consumer'], ['JO-15550', 'Jesus Ocampo', 'Home Office'], ['JK-15370', 'Jay Kimmel', 'Consumer'], ['BN-11470', 'Brad Norvell', 'Corporate'], ['DP-13165', 'David Philippe', 'Consumer'], ['TH-21550', 'Tracy Hopkins', 'Home Office'], ['AP-10915', 'Arthur Prichep', 'Consumer'], ['RS-19765', 'Roland Schwarz', 'Corporate'], ['SV-20365', 'Seth Vernon', 'Consumer'], ['CK-12325', 'Christine Kargatis', 'Home Office'], ['RD-19810', 'Ross DeVincentis', 'Home Office'], ['MR-17545', 'Mathew Reese', 'Home Office'], ['SC-20695', 'Steve Chapman', 'Corporate'], ['JF-15355', 'Jay Fein', 'Consumer'], ['EG-13900', 'Emily Grady', 'Consumer'], ['DS-13030', 'Darrin Sayre', 'Home Office'], ['PO-19195', 'Phillina Ober', 'Home Office'], ['SS-20875', 'Sung Shariari', 'Consumer'], ['PB-19105', 'Peter Bühler', 'Consumer'], ['RF-19735', 'Roland Fjeld', 'Consumer'], ['YC-21895', 'Yoseph Carroll', 'Corporate'], ['DC-13285', 'Debra Catini', 'Consumer'], ['CP-12340', 'Christine Phan', 'Corporate'], ['BF-11020', 'Barry Französisch', 'Corporate'], ['LH-17020', 'Lisa Hazard', 'Consumer'], ['CS-12250', 'Chris Selesnick', 'Corporate'], ['AJ-10795', 'Anthony Johnson', 'Corporate'], ['BV-11245', 'Benjamin Venier', 'Corporate'], ['DL-12865', 'Dan Lawera', 'Consumer'], ['BM-11785', 'Bryan Mills', 'Consumer'], ['LT-17110', 'Liz Thompson', 'Consumer'], ['JK-15730', 'Joe Kamberova', 'Consumer'], ['ES-14020', 'Erica Smith', 'Consumer'], ['RH-19495', 'Rick Hansen', 'Consumer'], ['CD-11920', 'Carlos Daly', 'Consumer'], ['HW-14935', 'Helen Wasserman', 'Corporate'], ['MC-18130', 'Mike Caudle', 'Corporate'], ['GM-14440', 'Gary McGarr', 'Consumer'], ['PJ-19015', 'Pauline Johnson', 'Consumer'], ['BW-11110', 'Bart Watters', 'Corporate'], ['TR-21325', 'Toby Ritter', 'Consumer'], ['PG-18820', 'Patrick Gardner', 'Consumer'], ['JL-15175', 'James Lanier', 'Home Office'], ['BM-11650', 'Brian Moss', 'Corporate'], ['EM-14095', 'Eudokia Martin', 'Corporate'], ['AF-10885', 'Art Foster', 'Consumer'], ['GA-14725', 'Guy Armstrong', 'Consumer'], ['CK-12760', 'Cyma Kinney', 'Corporate'], ['DP-13105', 'Dave Poirier', 'Corporate'], ['BK-11260', 'Berenike Kampe', 'Consumer'], ['SJ-20125', 'Sanjit Jacobs', 'Home Office'], ['CM-12445', 'Chuck Magee', 'Consumer'], ['AJ-10780', 'Anthony Jacobs', 'Corporate'], ['LS-16945', 'Linda Southworth', 'Corporate'], ['GP-14740', 'Guy Phonely', 'Corporate'], ['PK-18910', 'Paul Knutson', 'Home Office'], ['SM-20005', 'Sally Matthias', 'Consumer'], ['AG-10765', 'Anthony Garverick', 'Home Office'], ['PM-19135', 'Peter McVee', 'Home Office'], ['LL-16840', 'Lauren Leatherbury', 'Consumer'], ['JS-15595', 'Jill Stevenson', 'Corporate'], ['EL-13735', 'Ed Ludwig', 'Home Office'], ['PC-18745', 'Pamela Coakley', 'Corporate'], ['HL-15040', 'Hunter Lopez', 'Consumer'], ['MS-17365', 'Maribeth Schnelling', 'Consumer'], ['GB-14530', 'George Bell', 'Corporate'], ['JR-16210', 'Justin Ritter', 'Corporate'], ['BE-11335', 'Bill Eplett', 'Home Office'], ['SC-20050', 'Sample Company A', 'Home Office'], ['RW-19630', 'Rob Williams', 'Corporate'], ['SE-20110', 'Sanjit Engle', 'Consumer'], ['AH-10075', 'Adam Hart', 'Corporate'], ['JM-15535', 'Jessica Myrick', 'Consumer'], ['JJ-15760', 'Joel Jenkins', 'Home Office'], ['RK-19300', 'Ralph Kennedy', 'Consumer'], ['CG-12040', 'Catherine Glotzbach', 'Home Office'], ['RP-19270', 'Rachel Payne', 'Corporate'], ['KC-16255', 'Karen Carlisle', 'Corporate'], ['KH-16360', 'Katherine Hughes', 'Consumer'], ['GH-14665', 'Greg Hansen', 'Consumer'], ['SW-20275', 'Scott Williamson', 'Consumer'], ['JA-15970', 'Joseph Airdo', 'Consumer'], ['DL-12925', 'Daniel Lacy', 'Consumer'], ['LW-16990', 'Lindsay Williams', 'Corporate'], ['TB-21190', 'Thomas Brumley', 'Home Office'], ['BS-11800', 'Bryan Spruell', 'Home Office'], ['RW-19690', 'Robert Waldorf', 'Consumer'], ['TZ-21580', 'Tracy Zic', 'Consumer'], ['AS-10630', 'Ann Steele', 'Home Office'], ['TS-21340', 'Toby Swindell', 'Consumer'], ['SL-20155', 'Sara Luxemburg', 'Home Office'], ['MW-18235', 'Mitch Willingham', 'Corporate'], ['RD-19585', 'Rob Dowd', 'Consumer'], ['RA-19945', 'Ryan Akin', 'Consumer'], ['MT-17815', 'Meg Tillman', 'Consumer'], ['VG-21790', 'Vivek Gonzalez', 'Consumer'], ['JS-15880', 'John Stevenson', 'Consumer'], ['KM-16225', 'Kalyca Meade', 'Corporate'], ['HR-14770', 'Hallie Redmond', 'Home Office'], ['DE-13255', 'Deanra Eno', 'Home Office'], ['AG-10390', 'Allen Goldenen', 'Consumer'], ['JJ-15445', 'Jennifer Jackson', 'Consumer'], ['JH-15430', 'Jennifer Halladay', 'Consumer'], ['RD-19660', 'Robert Dilbeck', 'Home Office'], ['MO-17500', "Mary O'Rourke", 'Consumer'], ['NS-18640', 'Noel Staavos', 'Corporate'], ['DG-13300', 'Deirdre Greer', 'Corporate'], ['NF-18595', 'Nicole Fjeld', 'Home Office'], ['MG-17650', 'Matthew Grinstein', 'Home Office'], ['TS-21160', 'Theresa Swint', 'Corporate'], ['BD-11620', 'Brian DeCherney', 'Consumer'], ['CM-12160', 'Charles McCrossin', 'Consumer'], ['SN-20560', 'Skye Norling', 'Home Office'], ['EH-14005', 'Erica Hernandez', 'Home Office'], ['FO-14305', 'Frank Olsen', 'Consumer'], ['MS-17710', 'Maurice Satty', 'Consumer'], ['CC-12100', 'Chad Cunningham', 'Home Office'], ['DW-13540', 'Don Weiss', 'Consumer'], ['BT-11395', 'Bill Tyler', 'Corporate'], ['CY-12745', 'Craig Yedwab', 'Corporate'], ['BT-11485', 'Brad Thomas', 'Home Office'], ['PS-19045', 'Penelope Sewall', 'Home Office'], ['PV-18985', 'Paul Van Hugh', 'Home Office'], ['NM-18520', 'Neoma Murray', 'Consumer'], ['DL-13495', 'Dionis Lloyd', 'Corporate'], ['CS-12355', 'Christine Sundaresam', 'Consumer'], ['FH-14275', 'Frank Hawley', 'Corporate'], ['NC-18340', 'Nat Carroll', 'Consumer'], ['AA-10315', 'Alex Avila', 'Consumer'], ['LT-16765', 'Larry Tron', 'Consumer'], ['AP-10720', 'Anne Pryor', 'Home Office'], ['PM-18940', 'Paul MacIntyre', 'Consumer'], ['AT-10435', 'Alyssa Tate', 'Home Office'], ['CA-12055', 'Cathy Armstrong', 'Home Office'], ['HR-14830', 'Harold Ryan', 'Corporate'], ['BT-11530', 'Bradley Talbott', 'Home Office'], ['LH-16750', 'Larry Hughes', 'Consumer'], ['SW-20755', 'Steven Ward', 'Corporate'], ['SP-20620', 'Stefania Perrino', 'Corporate'], ['BF-11170', 'Ben Ferrer', 'Home Office'], ['KT-16480', 'Kean Thornton', 'Consumer'], ['BG-11695', 'Brooke Gillingham', 'Corporate'], ['GM-14680', 'Greg Matthias', 'Consumer'], ['EJ-14155', 'Eva Jacobs', 'Consumer'], ['NP-18700', 'Nora Preis', 'Consumer'], ['MH-18115', 'Mick Hernandez', 'Home Office'], ['JR-15700', 'Jocasta Rupert', 'Consumer'], ['SM-20950', 'Suzanne McNair', 'Corporate'], ['CC-12220', 'Chris Cortes', 'Consumer'], ['PF-19225', 'Phillip Flathmann', 'Consumer'], ['DC-12850', 'Dan Campbell', 'Consumer'], ['BD-11770', 'Bryan Davis', 'Consumer'], ['GM-14500', 'Gene McClure', 'Consumer'], ['TB-21355', 'Todd Boyes', 'Corporate'], ['JH-16180', 'Justin Hirsh', 'Consumer'], ['EB-13975', 'Erica Bern', 'Corporate'], ['QJ-19255', 'Quincy Jones', 'Corporate'], ['TC-21535', 'Tracy Collins', 'Home Office'], ['CS-12460', 'Chuck Sachs', 'Consumer'], ['HG-14965', 'Henry Goldwyn', 'Corporate'], ['LW-16825', 'Laurel Workman', 'Corporate'], ['MC-17575', 'Matt Collins', 'Consumer'], ['LP-17095', 'Liz Preis', 'Consumer'], ['EB-14170', 'Evan Bailliet', 'Consumer'], ['GZ-14545', 'George Zrebassa', 'Corporate'], ['CP-12085', 'Cathy Prescott', 'Corporate'], ['FG-14260', 'Frank Gastineau', 'Home Office'], ['LD-17005', 'Lisa DeCherney', 'Consumer'], ['AB-10255', 'Alejandro Ballentine', 'Home Office'], ['MN-17935', 'Michael Nguyen', 'Consumer'], ['JR-15670', 'Jim Radford', 'Consumer'], ['JF-15190', 'Jamie Frazer', 'Consumer'], ['CM-12115', 'Chad McGuire', 'Consumer'], ['AS-10045', 'Aaron Smayling', 'Corporate'], ['BP-11290', 'Beth Paige', 'Consumer'], ['ND-18370', 'Natalie DeCherney', 'Consumer'], ['LB-16735', 'Larry Blacks', 'Consumer'], ['KT-16465', 'Kean Takahito', 'Consumer'], ['HM-14860', 'Harry Marie', 'Corporate'], ['AB-10600', 'Ann Blume', 'Corporate'], ['SZ-20035', 'Sam Zeldin', 'Home Office'], ['MG-17890', 'Michael Granlund', 'Home Office'], ['JK-16120', 'Julie Kriz', 'Home Office'], ['PP-18955', 'Paul Prost', 'Home Office'], ['YS-21880', 'Yana Sorensen', 'Corporate'], ['KM-16375', 'Katherine Murray', 'Home Office'], ['AB-10105', 'Adrian Barton', 'Consumer'], ['H

Orders

In [33]:
from datetime import datetime

# 取得 df 中的訂單資料
print(df.columns)
orders_df = df[['Order ID', 'Order Date', 'Ship Date', 'Ship Mode', 'Customer ID']]


# orders_df.head()
# 將日期格式轉換為 datetime.date
orders_df['Order Date'] = pd.to_datetime(orders_df['Order Date'], format='%m/%d/%Y').dt.date
orders_df['Ship Date'] = pd.to_datetime(orders_df['Ship Date'], format='%m/%d/%Y').dt.date


orders_df = orders_df.drop_duplicates()

# orders_df
# 轉成 list 以便後續寫入
orders_list = orders_df.values.tolist()

# 寫入 Orders 資料表
with connection.cursor() as cursor:
    
    sql = """
        INSERT INTO orders (order_id, order_date, ship_date, ship_mode, customer_id) 
        VALUES (%s, %s, %s, %s, %s)
    """
    cursor.executemany(sql, orders_list)
    connection.commit()

Index(['Row ID', 'Order ID', 'Order Date', 'Ship Date', 'Ship Mode',
       'Customer ID', 'Customer Name', 'Segment', 'Country', 'City', 'State',
       'Postal Code', 'Region', 'Product ID', 'Category', 'Sub-Category',
       'Product Name', 'Sales', 'Quantity', 'Discount', 'Profit'],
      dtype='object')

C:\Users\student\AppData\Local\Temp\ipykernel_16392\636102154.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  orders_df['Order Date'] = pd.to_datetime(orders_df['Order Date'], format='%m/%d/%Y').dt.date
C:\Users\student\AppData\Local\Temp\ipykernel_16392\636102154.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  orders_df['Ship Date'] = pd.to_datetime(orders_df['Ship Date'], format='%m/%d/%Y').dt.date

Products

In [35]:
# 取得 df 中的產品資料
print(df.columns)
products_df = df[['Product ID', 'Product Name', 'Category', 'Sub-Category']]

# 轉成 list 以便後續寫入
products_df = products_df.drop_duplicates()

products_list = products_df.values.tolist()

# 寫入 Products 資料表
with connection.cursor() as cursor:
    
    sql = """
        INSERT INTO products (product_id, product_name, category, sub_category)
        VALUES (%s, %s, %s, %s)
    """
    cursor.executemany(sql, products_list)
    connection.commit()

Index(['Row ID', 'Order ID', 'Order Date', 'Ship Date', 'Ship Mode',
       'Customer ID', 'Customer Name', 'Segment', 'Country', 'City', 'State',
       'Postal Code', 'Region', 'Product ID', 'Category', 'Sub-Category',
       'Product Name', 'Sales', 'Quantity', 'Discount', 'Profit'],
      dtype='object')

OrderDetails

In [38]:
# 取得 df 中的訂單明細資料
print(df.columns)
orderdetails_df = df[['Row ID', 'Order ID', 'Product ID', 'Sales', 'Quantity', 'Discount', 'Profit']]

# 轉成 list 以便後續寫入
orderdetails_list = orderdetails_df.values.tolist()

# 寫入 OrderDetails 資料表
with connection.cursor() as cursor:
    
    sql = """
        INSERT INTO orderdetails (row_id, order_id, product_id, sales, quantity, discount, profit)
        VALUES (%s, %s, %s, %s, %s, %s, %s)
    """
    cursor.executemany(sql, orderdetails_list)
    connection.commit()

Index(['Row ID', 'Order ID', 'Order Date', 'Ship Date', 'Ship Mode',
       'Customer ID', 'Customer Name', 'Segment', 'Country', 'City', 'State',
       'Postal Code', 'Region', 'Product ID', 'Category', 'Sub-Category',
       'Product Name', 'Sales', 'Quantity', 'Discount', 'Profit'],
      dtype='object')